#!/bin/bash

#set -ex

curl -sL https://github.com/neovim/neovim/releases/download/stable/nvim-linux64.tar.gz -o /tmp/nvim.tar.gz > /dev/null
mkdir ~/.local
tar -xvf /tmp/nvim.tar.gz -C ~/.local --strip-components=1

sh -c 'curl -sfLo "${XDG_DATA_HOME:-$HOME/.local/share}"/nvim/site/autoload/plug.vim --create-dirs  https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

mkdir -p ~/.config/nvim
cp binder/binder_init.vim ~/.config/nvim/init.vim

mkdir -p ~/.config/qualia
cp binder/binder_config.py ~/.config/qualia/config.py

nvim --headless +PlugInstall +qall  >/dev/null 2>&1

#nvim ~/a.q.md
